- name: ansible demo
  hosts: localhost
  connection: local
  vars:
    URL: vars.sathu.google.com
  tasks:
  - name: print url
    ansible.builtin.debug:
      msg: URL is {{ URL }}

- name: print url demo-from task
  hosts: localhost
  connection: local
  tasks:
    - name: print url
      ansible.builtin.debug:
        msg: URL provided in task is {{ URL }}
      vars:
          URL: taskurl.google.com

- name: print default url
  hosts: localhost
  connection: local
  roles:
    - sample

- name: demo on registered variable
  hosts: localhost
  connection: local
  become: yes
  tasks:
    - name: check a package
      ansible.builtin.dnf:
        name: zlib
        state: installed
      register: out

    - name: print out
      ansible.builtin.debug:
        msg: "{{ out }}"



## Variable types:
#1. Plain Variable
#     url: example.com
#2. List Variable
##     url:
#      - url1.com
#      - url2.com
##3. Map Variable
#      domain.urls:
#        test: test.com
#        dev: dev.com


#
##variable supported data types:
#1. String
#2. Number
#3. Boolean



