- name: ansible demo
  hosts: localhost
  connection: local
  vars:
    URL: vars.sathu.google.com

  tasks:
    - name: print url
      ansible.builtin.debug:
        msg: URL is {{ URL }}

    - name: print url from task
      ansible.builtin.debug:
        msg: URL provided in task is {{ URL }}
        vars:
          URL: taskurl.google.com

