# conditions to define whether to skip it or not

- name: demo on condition
  hosts: localhost
  connection: local
  become: yes
  vars:
    to_install: true
  tasks:
    - name: print OS Redhat
      ansible.builtin.debug:
        msg: Redhat
      when: os == "redhat"

    - name: print OS Ubuntu
      ansible.builtin.debug:
        msg: Ubuntu
      when: os == "ubuntu"

    - name: Boolean condition
      ansible.builtin.debug:
        msg: "to-install is true"
      when: to_install


