- name: demo on tags
  hosts: localhost
  connection: local
  tasks:
    - name: install nginx
      ansible.builtin.debug:
        msg: nginx is installed
      tags:
        - install

    - name: start nginx
      ansible.builtin.debug:
        msg: nginx is started
      tags:
        - start