- name: filters demo
  hosts: localhost
  connection: local
  vars:
    x: 1, 2, 3
  tasks:
    - name: using filters
      ansible.builtin.debug:
        msg: first case {{ x | split(',') | first }}

    - name: using filters case_1
      ansible.builtin.debug:
        msg: second case {{ split[1] }}
      vars:
        split: "{{ x | split(',') }}"

    - name: using filters case_2
      ansible.builtin.debug:
        msg: third case {{ x.split(',')[1] }}