- name: handlers demo
  hosts: localhost
  connection: local
  tasks:
    - name: install zlib
      ansible.builtin.shell: ls
      notify:
        - say hi

  handlers:
    - name: say hi
      ansible.builtin.debug:
       msg: Iam notified