- name: handlers demo
  hosts: localhost
  connection: local
  tasks:
    - name: install zlib
      ansible.builtin.shell: ls
      notify:
        - get notified

      handlers:
        - name: get notified
          ansible.builtin.debug:
           msg: Iam notified